name: QuickAid
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
#  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  http: ^0.13.3
#  firebase_auth: ^3.3.20
#  firebase_core: ^1.18.0
  flutter_secure_storage: ^5.0.2
  flutter_lints: ^2.0.0
  flutter_svg: ^1.1.0
  velocity_x: ^3.3.0
  flutter_spinkit: ^5.1.0
  flutter_inset_box_shadow:
  settings_ui: ^2.0.2
  intl_phone_field: ^3.1.0
  extended_phone_number_input: ^1.0.2
  change_app_package_name: ^1.1.0

  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/images/
    - assets/icons/
